<?php
global $common_fields;
$common_fields = array("thisPage"=>"Операция",
			"username"=>"Имя пользователя",
			"password"=>"Пароль",
			"interface_revision"=>"Ревизия интерфейса",
			"interface_lang"=>"Язык интерфейса",
			"domain_name"=>"Имя домена. Обязательно только для операций с доменами");
$optional_fields = array("notpaid" => "Создать счёт как неоплаченный",
			"period"=>"Срок регистрации/продления",
			"descr"=>"Описание домена",
			"utf8"=>"Кодировка. При отсутствии используется кодировка CP1251");

$actions = array("pispInitiateTransfer" => "no",
"pispCheckDomain" => "no",
"pispWhois" => "no",
"pispRenewDomain" => "no",
"pispRedelegation" => "no",
"pispContactDetails" => "no",
"pispBalance" => "no",
"pispDomainMove" => "no",
"pispDomainRevoke" => "no",
"pispDomainInfo" => "no",
"pispGetContactDetails" => "no",
"pispCreateUser" => "no",
"pispAdminChange" => "no",
"pispAllDomainsInfo" => "no",
"pispCancelDomain" => "no",
"pispRegistryKey" => "no",
"pispGetDelegation" => "no",
"pispAddNameServer" => "no",
"pispDeleteNameServer" => "no",
"pispGetPrice" => "no",
"pispAddVerificationScan" => "no",
"pispDomainZoneAddAlias" => "no",
"pispDomainZoneAddCname" => "no",
"pispDomainZoneAddMX" => "no",
"pispDomainZoneAddNS" => "no",
"pispDomainZoneAddTXT" => "no",
"pispDomainZoneSRV" => "no",
"pispDomainZoneRmRR" => "no",
"pispDomainZoneUpdate" => "no",
"pispDomainZoneTuneFwd" => "no",
"pispDomainZoneTuneHost" => "no",
"pispDomainZoneInfo" => "no",);
?>